### ISSUE TITLE
Error with ide

### ISSUE THREAD

**Issue by Haz001** [Haz001/EnSim#1]
IDE comes out with error when opening 'helllo world.es'
Traceback (most recent call last):
  File "D:\GITHUB\EnSim\IDE\Python\IDE.py", line 19, in <module>
    Interpriter.interprit.tagger(cmds)
  File "D:\GITHUB\EnSim\IDE\Python\Interpriter.py", line 17, in tagger
    if(";" in parts_t[1]):
IndexError: list index out of range

**Comment by Haz001** [comment]
should be in if something in command blocks, also it is a list being sent
